server:
  port: 10002
spring:
  application:
    name: feign-consumer-2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

