server:
  port: 10101
  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: SLEUTH-APPLICATION-1
  zipkin:
    enabled: true

  sleuth:
    sampler:
      #  默认值为0.1f，现在为了测试设置100%采集
      percentage: 1
    # zipkkin dashboard的地址：通过真实IP地址访问
    # baseUrl: http://127.0.0.1:9411
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/

  # 如果使用mq作为通知方式
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
       

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  
  